name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_test:
    container:
      image: ghcr.io/esen-uas/suorb-dev:latest

  steps:
    - uses: actions/checkout@v2

    - name: build
      run: make build

    - name: test
      run: make test
